title: Camus
description: >-
  Camus is a high-level dynamically typed, multi-paradigm, interpreted programming language.

color_scheme: "camus" # Custom theme
logo: "/assets/images/camus-logo/camus-wordmark.svg"

version: "0.29.0"
github_username:  camus-lang
search_enabled: true

url: "https://camus-lang.com"
# theme: "just-the-docs"
footer_content: "This site uses Just The Docs, with modifications."

ga_tracking: "UA-109828853-2"

aux_links:
  "Contribute on GitHub":
    - "//github.com/camus-lang/Camus"

# Don't touch anything beyond this point

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
